# Generated by Django 4.2.6 on 2023-10-12 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('reward', models.FloatField()),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
