# Generated by Django 4.2.6 on 2023-10-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Keys', 'Keys'), ('Friend', 'Friend')], max_length=200),
        ),
    ]
