# Generated by Django 4.2.6 on 2023-10-24 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_lostitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='username',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
    ]
