# Generated by Django 4.2.6 on 2023-10-25 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_location_remove_lostitem_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Keys', 'Keys'), ('Friend', 'Friend')], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('reward', models.FloatField()),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
