# Generated by Django 4.2.6 on 2023-10-25 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_founditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='sub_date',
        ),
        migrations.AddField(
            model_name='founditem',
            name='found_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported found'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='reward',
            field=models.FloatField(blank=True),
        ),
    ]
