# Generated by Django 4.2.6 on 2023-11-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_description_founditem_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='drop_location_decription',
            new_name='drop_location_description',
        ),
    ]
