# Generated by Django 4.2.6 on 2023-11-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_drop_location_decription_location_drop_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='drop_location_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='new_hub',
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location')),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hub'),
        ),
    ]
