# Generated by Django 4.2.7 on 2023-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_location_drop_location_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Hub Location Description'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Hub Name'),
        ),
    ]
