# Generated by Django 4.2.4 on 2023-11-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_hub_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Keys', 'Keys'), ('Friend', 'Friend'), ('ID Card', 'ID Card'), ('Wallet', 'Wallet'), ('Cell Phones', 'Cell Phones'), ('Laptops/Tablets', 'Laptops/Tablets'), ('Headphones', 'Headphones'), ('Umbrellas', 'Umbrellas'), ('Clothing/Accessories', 'Clothing/Accessories'), ('Others', 'Others - Specify in description')], max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Keys', 'Keys'), ('Friend', 'Friend'), ('ID Card', 'ID Card'), ('Wallet', 'Wallet'), ('Cell Phones', 'Cell Phones'), ('Laptops/Tablets', 'Laptops/Tablets'), ('Headphones', 'Headphones'), ('Umbrellas', 'Umbrellas'), ('Clothing/Accessories', 'Clothing/Accessories'), ('Others', 'Others - Specify in description')], max_length=200),
        ),
    ]
