# Generated by Django 4.2.6 on 2023-11-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_founditem_category_alter_lostitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='reward',
            field=models.FloatField(default=0),
        ),
    ]
