# Generated by Django 4.2.4 on 2023-11-30 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_lostitem_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='reward',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
