# Generated by Django 4.2.6 on 2023-10-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
